[build]
  command = "bun install && bun run build"
  publish = "dist"
  environment = { NODE_VERSION = "20", USE_BUN = "1" }

[build.environment]
  NPM_FLAGS = "--version" # Engaña a Netlify para que no use npm